### ISSUE TITLE
vim8 provides cdo and ldo

### ISSUE THREAD

**Issue by kiryph** [Peeja/vim-cdo#7]
Is this plugin deprecated, due to vim8 :cdo and :ldo commands. See here 
http://vimhelp.appspot.com/version8.txt.html#new-items-8.
Or does this plugin provide further features not contained in vim8

**Comment by Peeja** [comment]
Ooh, I had no idea! I do mostly Clojure these days, so I'm usually working in Emacs now.

It looks like the only thing the new `:cdo` is missing that `:Cdo` does is offer a confirm option, but you can add some kind of confirmation into the command you run on your own.

I'd say this is now redundant, and particularly considering I'm not up to maintaining it any more since I barely touch Vim, I'll call it deprecated.
